# Generated by Django 4.2.2 on 2025-04-16 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_project_language_srsexport'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('action', models.TextField()),
                ('benefit', models.TextField()),
                ('acceptance_criteria', models.JSONField(blank=True, default=list)),
                ('version_number', models.IntegerField(default=1)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('generation_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User Stories',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['status', '-created_at'], 'verbose_name_plural': 'Requirements'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='deadline',
            new_name='deadline_end',
        ),
        migrations.RemoveField(
            model_name='project',
            name='operating_system',
        ),
        migrations.AddField(
            model_name='developmentplan',
            name='hourly_rates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mockup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mockup',
            name='generation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockup',
            name='generation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mockup',
            name='generation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockup',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mockup',
            name='version_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='deadline_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='generation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='generation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='generation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='operating_systems',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.requirement'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(choices=[('feature', 'Feature'), ('constraint', 'Constraint'), ('quality', 'Quality'), ('interface', 'Interface'), ('security', 'Security'), ('performance', 'Performance'), ('other', 'Other')], default='feature', max_length=50),
        ),
        migrations.AddField(
            model_name='requirementhistory',
            name='requirement_type',
            field=models.CharField(choices=[('feature', 'Feature'), ('constraint', 'Constraint'), ('quality', 'Quality'), ('interface', 'Interface'), ('security', 'Security'), ('performance', 'Performance'), ('other', 'Other')], default='feature', max_length=50),
        ),
        migrations.AddField(
            model_name='srstemplate',
            name='preview_image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='srstemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='srstemplate',
            name='template_type',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom'), ('regulatory', 'Regulatory'), ('industry', 'Industry Standard')], default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='developmentplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='developmentplanversion',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='requirementcomment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='requirementhistory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='srsexport',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='srstemplate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='UserStoryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('action', models.TextField()),
                ('benefit', models.TextField()),
                ('acceptance_criteria', models.JSONField(blank=True, default=list)),
                ('version_number', models.IntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.userstory')),
            ],
        ),
        migrations.AddField(
            model_name='userstory',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='api.requirement'),
        ),
        migrations.CreateModel(
            name='UmlDiagram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('diagram_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('generation_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uml_diagrams', to='api.developmentplanversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uml_diagrams', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='MockupHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('html_content', models.TextField(blank=True)),
                ('version_number', models.IntegerField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mockup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.mockup')),
            ],
        ),
        migrations.AddField(
            model_name='mockup',
            name='user_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mockups', to='api.userstory'),
        ),
    ]
