# Generated by Django 4.2.2 on 2025-04-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userstory_alter_requirement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='handle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='umldiagram',
            name='diagram_type',
            field=models.CharField(choices=[('class', 'Class Diagram'), ('sequence', 'Sequence Diagram'), ('activity', 'Activity Diagram'), ('component', 'Component Diagram')], default='class', max_length=50),
        ),
    ]
