# Generated by Django 4.2.2 on 2025-04-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_requirement_handle_alter_umldiagram_diagram_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='srsexport',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='handle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
