# Generated by Django 4.2.2 on 2025-05-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_srsexport_url_alter_requirement_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockup',
            name='last_associated_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockup',
            name='needs_regeneration',
            field=models.BooleanField(default=False),
        ),
    ]
