# Generated by Django 4.2.2 on 2025-05-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mockup_last_associated_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mockups_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='mockups_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='requirements_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='requirements_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='uml_diagrams_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='uml_diagrams_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='user_stories_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='user_stories_total',
            field=models.IntegerField(default=0),
        ),
    ]
