# Generated by Django 4.2.2 on 2025-05-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mockup_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mockups_generating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='requirements_generating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='uml_diagrams_generating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='user_stories_generating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='image',
            field=models.URLField(default='https://placehold.co/1600x500/EEE/31343C'),
        ),
        migrations.AlterField(
            model_name='project',
            name='srs_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.srstemplate'),
        ),
    ]
